import typing as t


_Direction = t.Literal["top", "bottom", "left", "right"]


_Attr = t.Literal[
    "align",
    "alt",
    "background-color",
    "background-height",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "background-size",
    "background-url",
    "background-width",
    "base-url",
    "border",
    "border-bottom",
    "border-color",
    "border-left",
    "border-radius",
    "border-right",
    "border-style",
    "border-top",
    "border-width",
    "bottom",
    "carouselId",
    "cellpadding",
    "cellspacing",
    "color",
    "container-background-color",
    "css-class",
    "direction",
    "fluid-on-mobile",
    "font-family",
    "font-size",
    "font-style",
    "font-weight",
    "full-width",
    "hamburger",
    "height",
    "href",
    "ico-align",
    "ico-close",
    "ico-color",
    "ico-font-family",
    "ico-font-size",
    "ico-line-height",
    "ico-open",
    "ico-padding",
    "ico-padding-bottom",
    "ico-padding-left",
    "ico-padding-right",
    "ico-padding-top",
    "ico-text-decoration",
    "ico-text-transform",
    "icon-align",
    "icon-height",
    "icon-padding",
    "icon-position",
    "icon-size",
    "icon-unwrapped-alt",
    "icon-unwrapped-url",
    "icon-width",
    "icon-wrapped-alt",
    "icon-wrapped-url",
    "inline",
    "inner-background-color",
    "inner-border",
    "inner-border-bottom",
    "inner-border-left",
    "inner-border-radius",
    "inner-border-right",
    "inner-border-top",
    "inner-padding",
    "inner-padding-bottom",
    "inner-padding-left",
    "inner-padding-right",
    "inner-padding-top",
    "left",
    "left-icon",
    "letter-spacing",
    "line-height",
    "max-height",
    "mobileWidth",
    "mode",
    "name",
    "navbarBaseUrl",
    "padding",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "rel",
    "right",
    "right-icon",
    "sizes",
    "src",
    "srcset",
    "table-layout",
    "target",
    "tb-border",
    "tb-border-radius",
    "tb-hover-border-color",
    "tb-selected-border-color",
    "tb-width",
    "text-align",
    "text-decoration",
    "text-padding",
    "text-transform",
    "thumbnails",
    "thumbnails-src",
    "title",
    "top",
    "usemap",
    "vertical-align",
    "width",
]


_Attrs = t.Dict[_Attr, t.Optional[str]]


__all__ = (
    "_Attr",
    "_Attrs",
    "_Direction",
)
